# Generated by Django 4.2.16 on 2026-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, default='', max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('env', models.CharField(choices=[('prod', 'prod'), ('test', 'test'), ('dev', 'dev')], default='test', max_length=16)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('tidb', 'TiDB')], default='mysql', max_length=16)),
                ('created_by', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dbs_instances',
                'unique_together': {('ip', 'port')},
            },
        ),
    ]
