# Generated by Django 4.2.16 on 2026-03-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('tidb', 'TiDB'), ('postgresql', 'PostgreSQL')], default='mysql', max_length=16),
        ),
    ]
